version: 1
groups:
  amy_subcortical_temporal:
    include_regex:
    - ^AMYGDALA_SUVR$
    - ^LEFT_AMYGDALA_SUVR$
    - ^RIGHT_AMYGDALA_SUVR$
    - ^HIPPOCAMPUS_SUVR$
    - ^LEFT_HIPPOCAMPUS_SUVR$
    - ^RIGHT_HIPPOCAMPUS_SUVR$
    exclude_regex: []
  mri_subcortical_temporal:
    include_regex:
    - ^AMYGDALA_VOLUME$
    - ^LEFT_AMYGDALA_VOLUME$
    - ^RIGHT_AMYGDALA_VOLUME$
    - ^HIPPOCAMPUS_VOLUME$
    - ^LEFT_HIPPOCAMPUS_VOLUME$
    - ^RIGHT_HIPPOCAMPUS_VOLUME$
    exclude_regex: []
  amy_subcortical_striatum_basal_ganglia:
    include_regex:
    - ^ACCUMBENS_AREA_SUVR$
    - ^LEFT_ACCUMBENS_AREA_SUVR$
    - ^RIGHT_ACCUMBENS_AREA_SUVR$
    - ^CAUDATE_SUVR$
    - ^LEFT_CAUDATE_SUVR$
    - ^RIGHT_CAUDATE_SUVR$
    - ^LEFT_PALLIDUM_SUVR$
    - ^PALLIDUM_SUVR$
    - ^RIGHT_PALLIDUM_SUVR$
    - ^LEFT_PUTAMEN_SUVR$
    - ^PUTAMEN_SUVR$
    - ^RIGHT_PUTAMEN_SUVR$
    exclude_regex: []
  mri_subcortical_striatum_basal_ganglia:
    include_regex:
    - ^ACCUMBENS_AREA_VOLUME$
    - ^LEFT_ACCUMBENS_AREA_VOLUME$
    - ^RIGHT_ACCUMBENS_AREA_VOLUME$
    - ^CAUDATE_VOLUME$
    - ^LEFT_CAUDATE_VOLUME$
    - ^RIGHT_CAUDATE_VOLUME$
    - ^LEFT_PALLIDUM_VOLUME$
    - ^PALLIDUM_VOLUME$
    - ^RIGHT_PALLIDUM_VOLUME$
    - ^LEFT_PUTAMEN_VOLUME$
    - ^PUTAMEN_VOLUME$
    - ^RIGHT_PUTAMEN_VOLUME$
    exclude_regex: []
  amy_subcortical_thalamus:
    include_regex:
    - ^LEFT_THALAMUS_PROPER_SUVR$
    - ^RIGHT_THALAMUS_PROPER_SUVR$
    - ^THALAMUS_PROPER_SUVR$
    exclude_regex: []
  mri_subcortical_thalamus:
    include_regex:
    - ^LEFT_THALAMUS_PROPER_VOLUME$
    - ^RIGHT_THALAMUS_PROPER_VOLUME$
    - ^THALAMUS_PROPER_VOLUME$
    exclude_regex: []
  amy_cerebral_cortex:
    include_regex:
    - ^CEREBRAL_WHITE_MATTER_SUVR$
    exclude_regex: []
  mri_cerebral_cortex:
    include_regex:
    - ^CEREBRAL_WHITE_MATTER_VOLUME$
    exclude_regex: []
  amy_cerebellum:
    include_regex:
    - ^CEREBELLUM_CORTEX_SUVR$
    - ^CEREBELLUM_WHITE_MATTER_SUVR$
    exclude_regex: []
  mri_cerebellum:
    include_regex:
    - ^CEREBELLUM_CORTEX_VOLUME$
    - ^CEREBELLUM_WHITE_MATTER_VOLUME$
    exclude_regex: []
  amy_ventricles:
    include_regex:
    - ^INF_LAT_VENT_SUVR$
    - ^LEFT_INF_LAT_VENT_SUVR$
    - ^RIGHT_INF_LAT_VENT_SUVR$
    - ^LATERAL_VENTRICLE_SUVR$
    - ^LEFT_LATERAL_VENTRICLE_SUVR$
    - ^RIGHT_LATERAL_VENTRICLE_SUVR$
    - ^CSF_SUVR$
    exclude_regex: []
  mri_ventricles:
    include_regex:
    - ^INF_LAT_VENT_VOLUME$
    - ^LEFT_INF_LAT_VENT_VOLUME$
    - ^RIGHT_INF_LAT_VENT_VOLUME$
    - ^LATERAL_VENTRICLE_VOLUME$
    - ^LEFT_LATERAL_VENTRICLE_VOLUME$
    - ^RIGHT_LATERAL_VENTRICLE_VOLUME$
    - ^CSF_VOLUME$
    exclude_regex: []
  amy_corpus_collosum_wm:
    include_regex:
    - ^CC_POSTERIOR_SUVR$
    - ^CC_MID_POSTERIOR_SUVR$
    - ^CC_CENTRAL_SUVR$
    - ^CC_MID_ANTERIOR_SUVR$
    - ^CC_ANTERIOR_SUVR$
    exclude_regex: []
  mri_corpus_collosum_wm:
    include_regex:
    - ^CC_POSTERIOR_VOLUME$
    - ^CC_MID_POSTERIOR_VOLUME$
    - ^CC_CENTRAL_VOLUME$
    - ^CC_MID_ANTERIOR_VOLUME$
    - ^CC_ANTERIOR_VOLUME$
    exclude_regex: []
  amy_brainstem:
    include_regex:
    - ^BRAINSTEM_SUVR$
    exclude_regex: []
  mri_brainstem:
    include_regex:
    - ^BRAINSTEM_VOLUME$
    exclude_regex: []
  amy_frontal_lobe:
    include_regex:
    - ^CTX_CAUDALMIDDLEFRONTAL_SUVR$
    - ^CTX_LH_CAUDALMIDDLEFRONTAL_SUVR$
    - ^CTX_RH_CAUDALMIDDLEFRONTAL_SUVR$
    - ^CTX_FRONTALPOLE_SUVR$
    - ^CTX_LH_FRONTALPOLE_SUVR$
    - ^CTX_RH_FRONTALPOLE_SUVR$
    - ^CTX_LATERALORBITOFRONTAL_SUVR$
    - ^CTX_LH_LATERALORBITOFRONTAL_SUVR$
    - ^CTX_RH_LATERALORBITOFRONTAL_SUVR$
    - ^CTX_LH_MEDIALORBITOFRONTAL_SUVR$
    - ^CTX_MEDIALORBITOFRONTAL_SUVR$
    - ^CTX_RH_MEDIALORBITOFRONTAL_SUVR$
    - ^CTX_LH_PARSOPERCULARIS_SUVR$
    - ^CTX_PARSOPERCULARIS_SUVR$
    - ^CTX_RH_PARSOPERCULARIS_SUVR$
    - ^CTX_LH_PARSORBITALIS_SUVR$
    - ^CTX_PARSORBITALIS_SUVR$
    - ^CTX_RH_PARSORBITALIS_SUVR$
    - ^CTX_LH_PARSTRIANGULARIS_SUVR$
    - ^CTX_PARSTRIANGULARIS_SUVR$
    - ^CTX_RH_PARSTRIANGULARIS_SUVR$
    - ^CTX_LH_ROSTRALMIDDLEFRONTAL_SUVR$
    - ^CTX_RH_ROSTRALMIDDLEFRONTAL_SUVR$
    - ^CTX_ROSTRALMIDDLEFRONTAL_SUVR$
    - ^CTX_LH_SUPERIORFRONTAL_SUVR$
    - ^CTX_RH_SUPERIORFRONTAL_SUVR$
    - ^CTX_SUPERIORFRONTAL_SUVR$
    exclude_regex: []
  mri_frontal_lobe:
    include_regex:
    - ^CTX_CAUDALMIDDLEFRONTAL_VOLUME$
    - ^CTX_LH_CAUDALMIDDLEFRONTAL_VOLUME$
    - ^CTX_RH_CAUDALMIDDLEFRONTAL_VOLUME$
    - ^CTX_FRONTALPOLE_VOLUME$
    - ^CTX_LH_FRONTALPOLE_VOLUME$
    - ^CTX_RH_FRONTALPOLE_VOLUME$
    - ^CTX_LATERALORBITOFRONTAL_VOLUME$
    - ^CTX_LH_LATERALORBITOFRONTAL_VOLUME$
    - ^CTX_RH_LATERALORBITOFRONTAL_VOLUME$
    - ^CTX_LH_MEDIALORBITOFRONTAL_VOLUME$
    - ^CTX_MEDIALORBITOFRONTAL_VOLUME$
    - ^CTX_RH_MEDIALORBITOFRONTAL_VOLUME$
    - ^CTX_LH_PARSOPERCULARIS_VOLUME$
    - ^CTX_PARSOPERCULARIS_VOLUME$
    - ^CTX_RH_PARSOPERCULARIS_VOLUME$
    - ^CTX_LH_PARSORBITALIS_VOLUME$
    - ^CTX_PARSORBITALIS_VOLUME$
    - ^CTX_RH_PARSORBITALIS_VOLUME$
    - ^CTX_LH_PARSTRIANGULARIS_VOLUME$
    - ^CTX_PARSTRIANGULARIS_VOLUME$
    - ^CTX_RH_PARSTRIANGULARIS_VOLUME$
    - ^CTX_LH_ROSTRALMIDDLEFRONTAL_VOLUME$
    - ^CTX_RH_ROSTRALMIDDLEFRONTAL_VOLUME$
    - ^CTX_ROSTRALMIDDLEFRONTAL_VOLUME$
    - ^CTX_LH_SUPERIORFRONTAL_VOLUME$
    - ^CTX_RH_SUPERIORFRONTAL_VOLUME$
    - ^CTX_SUPERIORFRONTAL_VOLUME$
    exclude_regex: []
  amy_cingulate:
    include_regex:
    - ^CTX_CAUDALANTERIORCINGULATE_SUVR$
    - ^CTX_LH_CAUDALANTERIORCINGULATE_SUVR$
    - ^CTX_RH_CAUDALANTERIORCINGULATE_SUVR$
    - ^CTX_ISTHMUSCINGULATE_SUVR$
    - ^CTX_LH_ISTHMUSCINGULATE_SUVR$
    - ^CTX_RH_ISTHMUSCINGULATE_SUVR$
    - ^CTX_LH_POSTERIORCINGULATE_SUVR$
    - ^CTX_POSTERIORCINGULATE_SUVR$
    - ^CTX_RH_POSTERIORCINGULATE_SUVR$
    - ^CTX_LH_ROSTRALANTERIORCINGULATE_SUVR$
    - ^CTX_RH_ROSTRALANTERIORCINGULATE_SUVR$
    - ^CTX_ROSTRALANTERIORCINGULATE_SUVR$
    exclude_regex: []
  mri_cingulate:
    include_regex:
    - ^CTX_CAUDALANTERIORCINGULATE_VOLUME$
    - ^CTX_LH_CAUDALANTERIORCINGULATE_VOLUME$
    - ^CTX_RH_CAUDALANTERIORCINGULATE_VOLUME$
    - ^CTX_ISTHMUSCINGULATE_VOLUME$
    - ^CTX_LH_ISTHMUSCINGULATE_VOLUME$
    - ^CTX_RH_ISTHMUSCINGULATE_VOLUME$
    - ^CTX_LH_POSTERIORCINGULATE_VOLUME$
    - ^CTX_POSTERIORCINGULATE_VOLUME$
    - ^CTX_RH_POSTERIORCINGULATE_VOLUME$
    - ^CTX_LH_ROSTRALANTERIORCINGULATE_VOLUME$
    - ^CTX_RH_ROSTRALANTERIORCINGULATE_VOLUME$
    - ^CTX_ROSTRALANTERIORCINGULATE_VOLUME$
    exclude_regex: []
  amy_parietal_lobe:
    include_regex:
    - ^CTX_INFERIORPARIETAL_SUVR$
    - ^CTX_LH_INFERIORPARIETAL_SUVR$
    - ^CTX_RH_INFERIORPARIETAL_SUVR$
    - ^CTX_LH_PRECUNEUS_SUVR$
    - ^CTX_PRECUNEUS_SUVR$
    - ^CTX_RH_PRECUNEUS_SUVR$
    - ^CTX_LH_SUPERIORPARIETAL_SUVR$
    - ^CTX_RH_SUPERIORPARIETAL_SUVR$
    - ^CTX_SUPERIORPARIETAL_SUVR$
    - ^CTX_LH_SUPRAMARGINAL_SUVR$
    - ^CTX_RH_SUPRAMARGINAL_SUVR$
    - ^CTX_SUPRAMARGINAL_SUVR$
    exclude_regex: []
  mri_parietal_lobe:
    include_regex:
    - ^CTX_INFERIORPARIETAL_VOLUME$
    - ^CTX_LH_INFERIORPARIETAL_VOLUME$
    - ^CTX_RH_INFERIORPARIETAL_VOLUME$
    - ^CTX_LH_PRECUNEUS_VOLUME$
    - ^CTX_PRECUNEUS_VOLUME$
    - ^CTX_RH_PRECUNEUS_VOLUME$
    - ^CTX_LH_SUPERIORPARIETAL_VOLUME$
    - ^CTX_RH_SUPERIORPARIETAL_VOLUME$
    - ^CTX_SUPERIORPARIETAL_VOLUME$
    - ^CTX_LH_SUPRAMARGINAL_VOLUME$
    - ^CTX_RH_SUPRAMARGINAL_VOLUME$
    - ^CTX_SUPRAMARGINAL_VOLUME$
    exclude_regex: []
  amy_temporal_lobe:
    include_regex:
    - ^CTX_BANKSSTS_SUVR$
    - ^CTX_LH_BANKSSTS_SUVR$
    - ^CTX_RH_BANKSSTS_SUVR$
    - ^CTX_ENTORHINAL_SUVR$
    - ^CTX_LH_ENTORHINAL_SUVR$
    - ^CTX_RH_ENTORHINAL_SUVR$
    - ^CTX_FUSIFORM_SUVR$
    - ^CTX_LH_FUSIFORM_SUVR$
    - ^CTX_RH_FUSIFORM_SUVR$
    - ^CTX_INFERIORTEMPORAL_SUVR$
    - ^CTX_LH_INFERIORTEMPORAL_SUVR$
    - ^CTX_RH_INFERIORTEMPORAL_SUVR$
    - ^CTX_LH_LINGUAL_SUVR$
    - ^CTX_LINGUAL_SUVR$
    - ^CTX_RH_LINGUAL_SUVR$
    - ^CTX_LH_MIDDLETEMPORAL_SUVR$
    - ^CTX_MIDDLETEMPORAL_SUVR$
    - ^CTX_RH_MIDDLETEMPORAL_SUVR$
    - ^CTX_LH_PARAHIPPOCAMPAL_SUVR$
    - ^CTX_PARAHIPPOCAMPAL_SUVR$
    - ^CTX_RH_PARAHIPPOCAMPAL_SUVR$
    - ^CTX_LH_SUPERIORTEMPORAL_SUVR$
    - ^CTX_RH_SUPERIORTEMPORAL_SUVR$
    - ^CTX_SUPERIORTEMPORAL_SUVR$
    - ^CTX_LH_TEMPORALPOLE_SUVR$
    - ^CTX_RH_TEMPORALPOLE_SUVR$
    - ^CTX_TEMPORALPOLE_SUVR$
    - ^CTX_LH_TRANSVERSETEMPORAL_SUVR$
    - ^CTX_RH_TRANSVERSETEMPORAL_SUVR$
    - ^CTX_TRANSVERSETEMPORAL_SUVR$
    exclude_regex: []
  mri_temporal_lobe:
    include_regex:
    - ^CTX_BANKSSTS_VOLUME$
    - ^CTX_LH_BANKSSTS_VOLUME$
    - ^CTX_RH_BANKSSTS_VOLUME$
    - ^CTX_ENTORHINAL_VOLUME$
    - ^CTX_LH_ENTORHINAL_VOLUME$
    - ^CTX_RH_ENTORHINAL_VOLUME$
    - ^CTX_FUSIFORM_VOLUME$
    - ^CTX_LH_FUSIFORM_VOLUME$
    - ^CTX_RH_FUSIFORM_VOLUME$
    - ^CTX_INFERIORTEMPORAL_VOLUME$
    - ^CTX_LH_INFERIORTEMPORAL_VOLUME$
    - ^CTX_RH_INFERIORTEMPORAL_VOLUME$
    - ^CTX_LH_LINGUAL_VOLUME$
    - ^CTX_LINGUAL_VOLUME$
    - ^CTX_RH_LINGUAL_VOLUME$
    - ^CTX_LH_MIDDLETEMPORAL_VOLUME$
    - ^CTX_MIDDLETEMPORAL_VOLUME$
    - ^CTX_RH_MIDDLETEMPORAL_VOLUME$
    - ^CTX_LH_PARAHIPPOCAMPAL_VOLUME$
    - ^CTX_PARAHIPPOCAMPAL_VOLUME$
    - ^CTX_RH_PARAHIPPOCAMPAL_VOLUME$
    - ^CTX_LH_SUPERIORTEMPORAL_VOLUME$
    - ^CTX_RH_SUPERIORTEMPORAL_VOLUME$
    - ^CTX_SUPERIORTEMPORAL_VOLUME$
    - ^CTX_LH_TEMPORALPOLE_VOLUME$
    - ^CTX_RH_TEMPORALPOLE_VOLUME$
    - ^CTX_TEMPORALPOLE_VOLUME$
    - ^CTX_LH_TRANSVERSETEMPORAL_VOLUME$
    - ^CTX_RH_TRANSVERSETEMPORAL_VOLUME$
    - ^CTX_TRANSVERSETEMPORAL_VOLUME$
    exclude_regex: []
  amy_occipital_lobe:
    include_regex:
    - ^CTX_CUNEUS_SUVR$
    - ^CTX_LH_CUNEUS_SUVR$
    - ^CTX_LH_PRECUNEUS_SUVR$
    - ^CTX_PRECUNEUS_SUVR$
    - ^CTX_RH_CUNEUS_SUVR$
    - ^CTX_RH_PRECUNEUS_SUVR$
    - ^CTX_LATERALOCCIPITAL_SUVR$
    - ^CTX_LH_LATERALOCCIPITAL_SUVR$
    - ^CTX_RH_LATERALOCCIPITAL_SUVR$
    - ^CTX_LH_PERICALCARINE_SUVR$
    - ^CTX_PERICALCARINE_SUVR$
    - ^CTX_RH_PERICALCARINE_SUVR$
    exclude_regex: []
  mri_occipital_lobe:
    include_regex:
    - ^CTX_CUNEUS_VOLUME$
    - ^CTX_LH_CUNEUS_VOLUME$
    - ^CTX_LH_PRECUNEUS_VOLUME$
    - ^CTX_PRECUNEUS_VOLUME$
    - ^CTX_RH_CUNEUS_VOLUME$
    - ^CTX_RH_PRECUNEUS_VOLUME$
    - ^CTX_LATERALOCCIPITAL_VOLUME$
    - ^CTX_LH_LATERALOCCIPITAL_VOLUME$
    - ^CTX_RH_LATERALOCCIPITAL_VOLUME$
    - ^CTX_LH_PERICALCARINE_VOLUME$
    - ^CTX_PERICALCARINE_VOLUME$
    - ^CTX_RH_PERICALCARINE_VOLUME$
    exclude_regex: []
  amy_sensory_motor_cortex:
    include_regex:
    - ^CTX_LH_PARACENTRAL_SUVR$
    - ^CTX_PARACENTRAL_SUVR$
    - ^CTX_RH_PARACENTRAL_SUVR$
    - ^CTX_LH_POSTCENTRAL_SUVR$
    - ^CTX_POSTCENTRAL_SUVR$
    - ^CTX_RH_POSTCENTRAL_SUVR$
    - ^CTX_LH_PRECENTRAL_SUVR$
    - ^CTX_PRECENTRAL_SUVR$
    - ^CTX_RH_PRECENTRAL_SUVR$
    exclude_regex: []
  mri_sensory_motor_cortex:
    include_regex:
    - ^CTX_LH_PARACENTRAL_VOLUME$
    - ^CTX_PARACENTRAL_VOLUME$
    - ^CTX_RH_PARACENTRAL_VOLUME$
    - ^CTX_LH_POSTCENTRAL_VOLUME$
    - ^CTX_POSTCENTRAL_VOLUME$
    - ^CTX_RH_POSTCENTRAL_VOLUME$
    - ^CTX_LH_PRECENTRAL_VOLUME$
    - ^CTX_PRECENTRAL_VOLUME$
    - ^CTX_RH_PRECENTRAL_VOLUME$
    exclude_regex: []
  demographic:
    include_regex:
    - PTID
    - PTDOB
    - PTGENDER
    - PTEDUCAT
    - PTRACCAT
    - PTETHCAT
    exclude_regex: []
