version: 1

experts:
  # ---------- Amyloid PET (SUVR) experts ----------
  amy_brainstem: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_brainstem_last_visit.csv
  amy_cerebellum: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_cerebellum_last_visit.csv
  amy_cerebral_cortex: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_cerebral_cortex_last_visit.csv
  amy_cingulate: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_cingulate_last_visit.csv
  amy_corpus_callosum_wm: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_corpus_collosum_wm_last_visit.csv
  amy_frontal_lobe: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_frontal_lobe_last_visit.csv
  amy_occipital_lobe: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_occipital_lobe_last_visit.csv
  amy_parietal_lobe: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_parietal_lobe_last_visit.csv
  amy_sensory_motor_cortex: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_sensory_motor_cortex_last_visit.csv
  amy_striatum_basal_ganglia: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_subcortical_striatum_basal_ganglia_last_visit.csv
  amy_subcortical_temporal: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_subcortical_temporal_last_visit.csv
  amy_subcortical_thalamus: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_subcortical_thalamus_last_visit.csv
  amy_temporal_lobe: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_temporal_lobe_last_visit.csv
  amy_ventricles: data/freesurfer_lastvisit_cv10/250826_DX_AMYLOID_amy_ventricles_last_visit.csv
