version: 1

experts:
  # ---------- MRI (volume) experts ----------
  mri_brainstem: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_brainstem_last_visit.csv
  mri_cerebellum: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_cerebellum_last_visit.csv
  mri_cerebral_cortex: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_cerebral_cortex_last_visit.csv
  mri_cingulate: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_cingulate_last_visit.csv
  mri_corpus_callosum_wm: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_corpus_collosum_wm_last_visit.csv
  mri_frontal_lobe: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_frontal_lobe_last_visit.csv
  mri_occipital_lobe: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_occipital_lobe_last_visit.csv
  mri_parietal_lobe: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_parietal_lobe_last_visit.csv
  mri_sensory_motor_cortex: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_sensory_motor_cortex_last_visit.csv
  mri_striatum_basal_ganglia: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_subcortical_striatum_basal_ganglia_last_visit.csv
  mri_subcortical_temporal: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_subcortical_temporal_last_visit.csv
  mri_subcortical_thalamus: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_subcortical_thalamus_last_visit.csv
  mri_temporal_lobe: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_temporal_lobe_last_visit.csv
  mri_ventricles: data/freesurfer_lastvisit/250826_DX_AMYLOID_mri_ventricles_last_visit.csv

  # ---------- Demographic expert ----------
  demographic: data/freesurfer_lastvisit/251020_DX_DEMOGRAPHIC_last_visit.csv
